exports.REPLACE_PLAYERS = 'pla-replace'
exports.CREATE_PLAYER = 'pla-create'
exports.UPDATE_PLAYER = 'pla-update'
exports.DELETE_PLAYER = 'pla-delete'
exports.UPDATE_PLAYER_AVATAR = 'pla-update-avatar'
